### ISSUE TITLE
一部ファイルでの BOM

### ISSUE THREAD

**Issue by clom** [lepus-ctf/lepus-api#1]
`/src/lepus/settings.py` にて行頭に Byte Order Mark がセットされていることを確認しました
これは大丈夫でしょうか。

**Comment by chibiegg** [comment]
:+1: LGTM

**Comment by nomuken** [comment]
ありがとうございます，確認します

**Comment by chibiegg** [comment]
マージしましたのでクローズします♪

**Comment by clom** [comment]
@chibiegg ありがとうございますー
